mdm:
    etisalat:
        protocol:
            version: "v13"
        company:
            code: aadc
            host: http://10.170.10.7
        kafka:
            brokers: 10.170.0.66:9096,10.170.0.67:9096,10.170.0.68:9096
            username: DIGITAL_CLIENT_DATAFLOWS-aadc-development_aadc
            password: a25f83ae9232446295fc100393c388ee
        mongo:
            uri: mongodb://platformadmin:3t1s4l4t-2022!@10.170.1.66:27017,10.170.1.67:27017,10.170.1.68:27017/oum_aadc?authSource=admin

logging:
    file: /home/mdm/mdm/logs/etisaliad-input/ms-heartbeat.log

job:
    unreachable: "0 0 * * * ?"
    active: "0 1 0/2 * * ?"