mdm:
    etisalat:
        protocol:
            version: "v13"
        company:
            code: addc
            host: http://10.170.4.130:8080
        kafka:
            brokers: 10.170.4.5:9096
            username: DIGITAL_CLIENT_DATAFLOWS-addc-development_addc
            password: 7f82a53ca85c41f2b0fd9372c0ada5ca
        mongo:
            uri: mongodb://platformadmin:3t1s4l4t-2022!@10.170.4.194:27017/addc?authSource=admin
            authDatabase: admin
logging:
    file: /home/mdm/mdm/logs/etisaliad-input/ms-heartbeat.log

job:
    unreachable: "0 0 * * * ?"
    active: "0 1 0/2 * * ?"

spring.cloud.stream.kafka.binder.consumerProperties:
  session.timeout.ms: 120000
  max.poll.interval.ms: 300000
  max.poll.records: 1