version: "3"
services:
  oum-web-addc:
    image: 'docksdtr.indra.es/addcmn-10.3/oum/production_addc/oum-web:latest'
    ports:
      - '8080:8080'
    container_name: 'oum-web-addc-2'
    networks:
      - oum_main
    hostname: OUM-ADDC-2
    volumes:
      - /home/au_addc/oum_deploy/volumes/oum_addc/report:/mdm/report
    extra_hosts:
      - "etisalat-pro.onesaitplatform.com:10.170.0.67"
networks:
    oum_main:
        external: true

