mdm:
  etisalat:
    company:
      code: ${COMPANY-CODE}
      host: ${COMPANY-HOST}
    kafka:
      brokers: ${KAFKA-BROKERS}
      username: ${KAFKA-USERNAME}
      password: ${KAFKA-PASSWORD}
    mongo:
      uri: ${MONGO-URI}
      authDatabase: ${MONGO-DATABASE}
