apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-oum-task-listener
  name: ms-oum-task-listener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-oum-task-listener
  template:
    metadata:
      labels:
        app: ms-oum-task-listener
    spec:
      containers:
      - image: ms-oum-task-listener:v1
        imagePullPolicy: Never
        name: ms-oum-task-listener