mdm:
  etisalat:
    company:
      code: aadc
    kafka:
      brokers: 10.170.5.2:9096
      username: DIGITAL_CLIENT_DATAFLOWS-aadc-development_aadc
      password: bca7b40878b64677a4a45ee557227875
    mongo:
      uri: mongodb://platformadmin:3t1s4l4t-D3V-2022!@10.170.5.66:27017/aadc?authSource=admin
